name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: actions/checkout

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download text file from build job
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: ./artifacts

      - name: display hello-txt contents
        run: cat ./artifact/hello.txt